version: '3.8'

services:
  discord-bot:
    image: oven/bun:latest
    container_name: discord-bot
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    command: sh -c "bun install && bun run src/index.ts"
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - CHANNEL_ID=${CHANNEL_ID}
      - NODE_ENV=production
      - TZ=America/New_York  # Set timezone to EST
    restart: unless-stopped
