version: '3.8'

services:
  discord-bot:
    image: jarredsumner/bun:latest
    container_name: discord-bot
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    command: sh -c "bun install && bun run src/index.ts"
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - CHANNEL_ID=${CHANNEL_ID}
      - NODE_ENV=production
    restart: unless-stopped
