services:
  discord-bot:
    build: .
    container_name: discord-bot
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - CHANNEL_ID=${CHANNEL_ID}
      - NODE_ENV=production
    restart: unless-stopped
